---
- name: Validate iodined config
  fail: 
    msg: "Must set value for `iodined_passord` if `iodined_enabled`"
  when: iodined_enabled and iodined_password is undefined

- name: Enable iodined service
  service: name=iodined enabled=yes

- name: Enable iodined in service config
  replace:
    path: /etc/default/iodine
    regexp: '^START_IODINED="false"$'
    replace: 'START_IODINED="true"'

- name: Set iodined arguments
  replace:
    path: /etc/default/iodine
    regexp: '^IODINED_ARGS=""$'
    replace: "IODINED_ARGS=\"{{ iodined_ip_address }} {{ iodined_domain }}\""
  notify: restart iodined

- name: Set iodined password
  replace:
    path: /etc/default/iodine
    regexp: '^IODINED_PASSWORD=""$'
    replace: "IODINED_PASSWORD=\"{{ iodined_password }}\""
