---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: enable-iodined.yml
  when: iodined_enabled

- include: disable-iodined.yml
  when: not iodined_enabled
